package com.planner.entities;

// default package
// Generated Mar 10, 2018 12:35:08 AM by Hibernate Tools 5.2.3.Final

import java.sql.Time;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name = "agenda", catalog = "planner")
public class Agenda implements java.io.Serializable {

    private int id;
    private Room room;
    private String description;
    private Date startDate;
    private Date endDate;
    private Time startTime;
    private Time endTime;
    private int duration;
    private int priority;
    private char isConfidential;
    private char isRepetetive;
    private Set<Employee> employees = new HashSet<Employee>(0);

    public Agenda() {
    }

    public Agenda(int id, String description, Date startDate, Date endDate, Time startTime, Time endTime, int duration,
                  int priority, char isConfidential, char isRepetetive) {
        this.id = id;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
        this.priority = priority;
        this.isConfidential = isConfidential;
        this.isRepetetive = isRepetetive;
    }

    public Agenda(int id, Room room, String description, Date startDate, Date endDate, Time startTime, Time endTime,
                  int duration, int priority, char isConfidential, char isRepetetive, Set<Employee> employees) {
        this.id = id;
        this.room = room;
        this.description = description;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.duration = duration;
        this.priority = priority;
        this.isConfidential = isConfidential;
        this.isRepetetive = isRepetetive;
        this.employees = employees;
    }


    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "roomId")
    public Room getRoom() {
        return this.room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    @Column(name = "description", nullable = false, length = 145)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "startDate", nullable = false, length = 10)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "endDate", nullable = false, length = 10)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "startTime", nullable = false, length = 8)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "endTime", nullable = false, length = 8)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }

    @Column(name = "duration", nullable = false)
    public int getDuration() {
        return this.duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    @Column(name = "priority", nullable = false)
    public int getPriority() {
        return this.priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    @Column(name = "isConfidential", nullable = false, length = 1)
    public char getIsConfidential() {
        return this.isConfidential;
    }

    public void setIsConfidential(char isConfidential) {
        this.isConfidential = isConfidential;
    }

    @Column(name = "isRepetetive", nullable = false, length = 1)
    public char getIsRepetetive() {
        return this.isRepetetive;
    }

    public void setIsRepetetive(char isRepetetive) {
        this.isRepetetive = isRepetetive;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "agenda_mem", catalog = "planner", joinColumns = {
            @JoinColumn(name = "agendaId", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "employeeId", nullable = false, updatable = false)})
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

}
