package com.planner.entities;

// default package
// Generated Mar 10, 2018 12:35:08 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "planner")
public class Room implements java.io.Serializable {

	private int id;
	private String name;
	private String location;
	private int capacity;
	private Set<MeetingRequests> meetingRequestses = new HashSet<>(0);
	private Set<Agenda> agendas = new HashSet<Agenda>(0);

	public Room() {
	}

	public Room(int id, String name, int capacity) {
		this.id = id;
		this.name = name;
		this.capacity = capacity;
	}

	public Room(int id, String name, String location, int capacity, Set<MeetingRequests> meetingRequestses,
				Set<Agenda> agendas) {
		this.id = id;
		this.name = name;
		this.location = location;
		this.capacity = capacity;
		this.meetingRequestses = meetingRequestses;
		this.agendas = agendas;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", length = 45)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "capacity", nullable = false)
	public int getCapacity() {
		return this.capacity;
	}

	public void setCapacity(int capacity) {
		this.capacity = capacity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<MeetingRequests> getMeetingRequestses() {
		return this.meetingRequestses;
	}

	public void setMeetingRequestses(Set<MeetingRequests> meetingRequestses) {
		this.meetingRequestses = meetingRequestses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Agenda> getAgendas() {
		return this.agendas;
	}

	public void setAgendas(Set<Agenda> agendas) {
		this.agendas = agendas;
	}

}
